class SurveyForm

  SPENDING_ATTRS = %i[
    credit_score
    will_apply_for_loan_true
    will_apply_for_loan_false
    personal_spending
    has_business_with_ein
    has_business_without_ein
    has_business_no_business
  ]

  attr_accessor :main_passenger, :companion
  attr_reader   :has_companion

  # The checkboxes generated by Rails's form will submit "1" for true
  # and "0" for false, both of which Ruby will treat as truthy - so clean
  # it up here:
  def has_companion=(bool)
    @has_companion = bool == "0" ? false : !!bool
  end

  def has_companion?
    self.has_companion
  end

end
